name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: debian-latest

    steps:
    - uses: actions/checkout@v4
    - name: build docker image
      run: docker build -t siliconecb.cc .
